services:
  db:
    image: postgres:16-alpine
    container_name: udp_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: udp
      POSTGRES_PASSWORD: udp_password
      POSTGRES_DB: udp
    volumes:
      - udp_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro

volumes:
  udp_pgdata:
